# fly.toml file generated for solitary-leaf-5490 on 2023-04-05T15:59:40+03:00

app = "solitary-leaf-5490"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "arn"
processes = []

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
